version: '3.9'

services:

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG}
    ports:
      - 9200:9200
    expose:
      - 9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    networks:
      - elastic

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${TAG}
    ports:
      - 5601:5601
    expose:
      - 5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=https://elasticsearch:9200
    networks:
      - elastic

networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch-data:
    driver: local