version: "2"

services:

  database:
    container_name: database
    image: postgres:latest
    ports:
      - "${DB_PORT:-5432}:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: Q12345q
      POSTGRES_USER: stego
      POSTGRES_DB: stego
    labels:
      co.elastic.logs/module: postgresql
      co.elastic.metrics/module: postgresql
    networks:
      - stego

  cache:
    container_name: redis
    image: redis:latest
    ports:
      - "${CACHE_PORT:-6379}:6379"
    restart: always
    environment:
      - REDIS_PASSWORD=Q12345q
    networks:
      - stego
    labels:
      co.elastic.logs/module: redis
      co.elastic.metrics/module: redis

networks:
  stego:
    driver: bridge
